name: Setup Pipeline Toolchain
description: 'Sets up Python + Node toolchain, caches packages, and installs dependencies'

runs:
  using: 'composite'

  steps:
    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v5.4.0
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          pipeline/requirements.txt
          api/requirements.txt

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black autoflake isort doc8 flake8 flake8-pytest-style flake8-bugbear flake8-comprehensions flake8-print darglint bandit pylint
        pip install -r pipeline/requirements.txt
        if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
      shell: bash
